name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master  # Set a branch to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build with Jekyll
      uses: ghcr.io/actions/jekyll-build-pages@v1.0.9
      with:
        source: .
        destination: ./_site